### ISSUE TITLE
[Map] CTF-Braveheart

### ISSUE THREAD

**Issue by SeriousBuggie** [unreal-archive/unreal-archive-data#1113]
Too many copies of same map:
https://unrealarchive.org/files/3c/3c19b7a06a205d5103a880b63c5babc6001480a0.html

---
URL: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/B/ctf-braveheart_af10380b.html
Hash: af10380b7ce09fbf465801c92222566779e4bd6a
Current name: CTF-Braveheart

**Comment by OjitroC** [comment]
Whilst indeed all four maps are the same, each archive is different (two of the four have different content (presence or absence of readme/screenshots) and in the other two cases the archive itself is different (zip and rar)).

**Comment by NeonKnightOA** [comment]
So this is a non-issue then?

**Comment by OjitroC** [comment]
In my opinion (FWIW), yes it's a non issue - the purpose of UA is to preserve archives of conent rather than content per se - so if there are muliple archives with the same map (for example) but slightly different other content then I don't see that as an issue.  If storage of content ever becomes a problem then it might be something to look at - otherwise no.

**Comment by shrimpza** [comment]
Yes, it's intended that content is allowed to be duplicated several times. This is why the files page links to several different pages in this case - that file is included in a bunch of packages as @OjitroC says. It prevents storage of duplicate packages, but if the same file exists in several packages with subtle differences, it's going to store them all.

From a general archiving point of view, they all contain slightly different stuff, so I don't really want to be the arbiter of what's correct and what's not, or rather what we deem worth archiving and everything else gets thrown away/lost.
