### ISSUE TITLE
[Map] CTFM-Helloween

### ISSUE THREAD

**Issue by DxTrEm3Fx** [unreal-archive/unreal-archive-data#1563]
I'm the original author of this map and whoever created the CTFM version and uploaded to your site didn't have permission.

---
URL: https://unrealarchive.org/maps/unreal-tournament/multi-team-ctf/H/ctfm-helloween_6c9f3601.html
Hash: 6c9f3601c322dad43affa5c38847d35d17de4ebf
Current name: CTFM-Helloween

**Comment by shrimpza** [comment]
Hello

So nobody actually uploaded this, it was automatically collected from various sources at ut-files.com, medor.no-ip.org, and uttexture.com, where it seems to have originally existed for many years.

Do you want this file delisted? I'm simply asking because your wording is a statement, not a question or specific request.


As for the other places this map exists, I can't do anything about those unfortunately.

**Comment by DxTrEm3Fx** [comment]
No, that’s fine. I didn’t even think I would receive a response. Just leave it up; sorry to bother you. 
Thank you.
