### ISSUE TITLE
[Map] DM-Godforsaken-[IV]-

### ISSUE THREAD

**Issue by Alien1V1breeD** [unreal-archive/unreal-archive-data#2296]
This is not the creator of the map as it is stated here. I am. (alien (massacre) breed). This needs to be taken down. Someone is claiming to have been responsible for my hundreds of hours of work. Not cool!

Below are the original locations that this map was submitted, by the original creator, me. You will not find earlier upload dates at any other download locations.
(new gamebanana.com account) https://gamebanana.com/members/1665945 (Alien~Breed user name)
(older gamebanana.com account) https://gamebanana.com/mods/56650 (Massacre username)
https://www.utzone.de/forum/downloads.php?do=file&id=4574 (Alien(massacre)Breed username)

---
URL: https://unrealarchive.org/maps/unreal-tournament-2004/deathmatch/G/dm-godforsaken-iv-_2d72091f.html
Hash: 2d72091fa565e08c4e8bf1e0a5fffd86c1a3eb94
Current name: DM-Godforsaken-[IV]-

**Comment by shrimpza** [comment]
Hi

The wrong author has been assigned to this map by accident. It seems it's got no author assigned, but it got auto-aliased to the wrong person due to a bug on the website. I can set the author to you correctly (I verified - it's the same file as available through GameBanana), or do you want me to de-list it still?

If not de-listing, which author name do you want it under?

![image](https://user-images.githubusercontent.com/6191747/215457741-1a6bb0d0-0ad4-48ae-a69c-e4cfbc2ffdf4.png)

**Comment by shrimpza** [comment]
Same with the other report, by the way.

**Comment by shrimpza** [comment]
There are other maps by author Massacre: https://unrealarchive.org/authors/massacre.html

**Comment by shrimpza** [comment]
Closing this and #2295 due to lack of further feedback.

Changed maps author to `Alien~Breed`, as they do not seem to be "stolen" but rather the author, as per their own description and provided GameBanana links provided here and actual map content, has changed their name over time from Massacre to Alien~Breed.
