### ISSUE TITLE
[Map] DM-Infernus

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2792]
Not an Unreal map - it's a UT3 map.

odd that it should have been parsed as Unreal?

---
URL: https://unrealarchive.org/maps/unreal/deathmatch/I/dm-infernus_d227f9c2.html
Hash: d227f9c2aa2921a054e44488ba89683766a4097c
Current name: DM-Infernus

**Comment by shrimpza** [comment]
Very interesting, thanks. Will fix.

**Comment by shrimpza** [comment]
Also fixed.

I've noticed some unit tests around game detection failing randomly too, and on investigating it seems I added some code to detect content containing "227" anywhere in the file path as being Unreal.

Since submissions use a random temporary path, those could sometimes randomly contain `227` in them.

Fixed the bug.
