### ISSUE TITLE
Content recognition, map sorting issue?

### ISSUE THREAD

**Issue by t3r6** [unreal-archive/unreal-archive-data#2830]
Sometimes the pipeline does not want to accept maps and says "No new content found in file".

However, I can't find similar maps on the website.
For example, the very first version of Asthenosphere and it's preview versions AS-AsthenosphereSE_preview and AS-AsthenosphereSE_preview2c. The size of the maps is different:

AS-Asthenosphere (v1.0) - 8,000,180
AS-AsthenosphereSE_preview.unr - 11,862,812
AS-AsthenosphereSE_preview2c.unr - 11,860,005

![image](https://github.com/unreal-archive/unreal-archive-data/assets/35698062/8505450e-fb18-4fd4-9da8-ba3e50808730)

**P.S.** I managed to notice one of the maps under Variations in https://unrealarchive.org/maps/unreal-tournament/assault/A/as-asthenospherese_e32bc5d6.html
https://unrealarchive.org/maps/unreal-tournament/assault/A/as-asthenospherese_preview2c_2257ad6a.html

But why does it not show up in the general Assault map list nor in the search?
https://unrealarchive.org/maps/unreal-tournament/assault/A/index.html
The same issue with some other maps like AS-Rikers-Island that I can only find under AS-Rikers-Island-][ Variation and not under the general list:

https://unrealarchive.org/maps/unreal-tournament/assault/R/as-rikers-island_172b7c3a.html
https://unrealarchive.org/maps/unreal-tournament/assault/R/as-rikers-island_1b01cba5.html

It seems that those maps were not indexed on the website and makes them almost impossible to find. If it is some sort of a website feature, I would be nice to have an option to see all of the maps.

**Comment by shrimpza** [comment]
When "no new content" is returned, it means the exact same files already exist - not just that they're the same name or something, but identical files.

If they're not showing up the in main list, its because they're variations. The number of variations of this map in the main lists seem to indicate that the variations system is trying to do its thing and sometimes works and others doesn't. These should honestly all be flagged as variations of the original file from March 2000 if we were doing it properly.

The case of AS-Rikers-Island and AS-Rikers-Island][ was a bug, I've corrected that one, both will be listed now.
