### ISSUE TITLE
Can't upload certain UT3 map packs

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3056]
I'm not able to upload [UNK Map Pack 1](https://drive.google.com/file/d/1eFdRIpEvgTTYm-SA-VRAB4Ujj9RwIpX8/view?usp=drive_link) and [UNK Map Pack 2](https://drive.google.com/file/d/1Mw1Io67lMijDfrycJc5vJqZYKw1ZBNUP/view?usp=drive_link) due to website not recognizing any content info in them.

**Comment by shrimpza** [comment]
As much as I prefer to not do it - had to force type to Map Pack, since they contain various mutator-like things, so it couldn't be sure they were just map packs.

https://unrealarchive.org/mappacks/unreal-tournament-3/warfare/U/unk-mappack-vol1_8507ae0c.html
https://unrealarchive.org/mappacks/unreal-tournament-3/warfare/U/unk-mappack-vol2_e27f30d8.html

**Comment by UnrealGGecko** [comment]
Can't be helped really, some mappers want to also include custom weapons in their map :/
