### ISSUE TITLE
[Map] CTF[SP]MonsterCity

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#384]
This map requires package "AssaultAdmin" to run - no idea what it is!

From the UEd 2.2 log 
Log: New File, Existing Package (Package MyLevel, Package CTF[SP]MonsterCity)
Warning: Failed to load "AssaultAdmin": Can't find file for package "AssaultAdmin"..
Warning: Failed to load "AssaultCTF": Can't find file for package "AssaultAdmin"..
Warning: Failed to load "C:\UnrealTournament\Maps\Current\CTF[SP]MonsterCity.unr": Can't find file for package "AssaultAdmin"..

---
Hash: dff22c392a49ae26a30d9f53419c49023c8ae5b5
Current name: CTF[SP]MonsterCity

**Comment by shrimpza** [comment]
The problem is that `AssaultCTF` is not included in the package either. So since `AssaultAdmin` is needed by `AssaultCTF`, there's no way to indicate on the dependencies list that the file is needed.

I can't seem to find AssaultCTF or AssaultAdmin included in anything in the archive at the moment...

**Comment by OjitroC** [comment]
I see - a bit surprising that AssaultCTF isn't included with any other [SP] map.  I have it and must have got it from Sniper's Paradise (where the [SP] maps come from).  Less surprised about AssaultAdmin as I couldn't find it on Sniper's Paradise anywhere - a pity really as it means this map can't be played or edited.
